version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: oxgroup_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oxgroup
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: oxgroup_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/oxgroup
      JWT_SECRET: secret123
      JWT_EXPIRES_IN: 1d
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

volumes:
  postgres_data:
